name: Deploy to Bluehost

on:
  push:
    branches:
      - main  # Change to your main branch if needed
      - natalia-pc
      - natalia-mac

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Bluehost via FTP
        uses: SamKirkland/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_PATH }}
